In [ ]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5])

In [ ]:
print(a)

[1 2 3 4 5]


In [ ]:
out=np.array([[x for x in range(2,21,2)],[x for x in range(1,21,2)]])

In [ ]:
out

array([[ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
       [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19]])

In [ ]:
out=out*2

In [ ]:
out

array([[ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40],
       [ 2,  6, 10, 14, 18, 22, 26, 30, 34, 38]])

In [ ]:
out.shape

(2, 10)

In [ ]:
out2=np.array([[x for x in range(9,0,-2)],[x for x in range(10,1,-2)]])

In [ ]:
out2

array([[ 9,  7,  5,  3,  1],
       [10,  8,  6,  4,  2]])

In [ ]:
out2.ndim

2

In [ ]:
grades=np.array([[70,71,72],[80,81,82],[90,91,92],[10,11,12]])

In [ ]:
grades

array([[70, 71, 72],
       [80, 81, 82],
       [90, 91, 92],
       [10, 11, 12]])

In [ ]:
grades[0].max()

72

In [ ]:
grades.min()

10

In [ ]:
grades.sum()

762

In [ ]:
grades.mean()

63.5

In [ ]:
grades.std()

31.135456744147284

In [ ]:
grades.mean(axis=0)

array([62.5, 63.5, 64.5])

In [ ]:
out3=out2.copy()

In [ ]:
out3

array([[ 9,  7,  5,  3,  1],
       [10,  8,  6,  4,  2]])

In [ ]:
arr1=np.array([1,2,3])

In [ ]:
arr2=arr

array([1, 2, 3])

In [ ]:
a=np.arange(1,10,2)

In [ ]:
a

array([1, 3, 5, 7, 9])

In [ ]:
b=a.view()#shallow copy

In [ ]:
b[2]=b[2]*6

In [ ]:
b

array([ 1,  3, 36,  7,  9])

In [ ]:
a

array([ 1,  3, 36,  7,  9])

In [ ]:
c=a.copy()#deepcopy

In [ ]:
c[1]=4

In [ ]:
c

array([ 1,  4, 36,  7,  9])

In [ ]:
a

array([ 1,  3, 36,  7,  9])

In [ ]:
num1=np.array([1,2,3])
num2=np.array([4,5,6])

In [ ]:
np.add(num1,num2)

array([5, 7, 9])

In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr[0]


array([1, 2, 3, 4, 5])

In [ ]:
arr[::2]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [ ]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
arr[1:3]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr[2,1:3]

array([12, 13])

In [ ]:
list1=list(arr[2])

In [ ]:
list1.reverse()

In [ ]:
list1

[15, 14, 13, 12, 11]

In [ ]:
arr[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [ ]:
list2=list(arr[3])

In [ ]:
arr[3].max()

20

In [ ]:
arr[3].min()

16

In [ ]:
arr[3].mean()

18.0

In [ ]:
arr[3].sum()

90

In [ ]:
arr[3].std()

1.4142135623730951

In [ ]:
arr[3].var()

2.0

In [ ]:
np.log10(arr[0])

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ])

In [ ]:
np.log2(arr[0])

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809])

In [ ]:
np.log(arr[0])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [ ]:
grades

array([[70, 71, 72],
       [80, 81, 82],
       [90, 91, 92],
       [10, 11, 12]])

In [ ]:
g1=grades.copy()

In [ ]:
g1.reshape(4,5)

ValueError: cannot reshape array of size 12 into shape (4,5)

In [ ]:
g1.reshape(3,4)

array([[70, 71, 72, 80],
       [81, 82, 90, 91],
       [92, 10, 11, 12]])

In [ ]:
g1.reshape(2,3)

ValueError: cannot reshape array of size 12 into shape (2,3)

In [ ]:
np.transpose(g1)

array([[70, 80, 90, 10],
       [71, 81, 91, 11],
       [72, 82, 92, 12]])

In [ ]:
g1

array([[70, 71, 72],
       [80, 81, 82],
       [90, 91, 92],
       [10, 11, 12]])